import Guidon

#print axioms Guidon.projection_neutral
#print axioms Guidon.projection_gain
#print axioms Guidon.training_progress
#print axioms Guidon.normalized_training_progress
#print axioms Guidon.normalized_guide_progress
#print axioms Guidon.guide_nonworsening
#print axioms Guidon.correction_bounded
#print axioms Guidon.weights_positive
#print axioms Guidon.perturbation_energy
#print axioms Guidon.conditional_descent
#print axioms Guidon.guide_loss_comparison
#print axioms Guidon.evaluation_noninterference
#print axioms Guidon.generalization_counterexample
#print axioms Guidon.quadratic_optimality
#print axioms Guidon.quadratic_optimum_attained
#print axioms Guidon.guide_progress
#print axioms Guidon.zero_radius
#print axioms Guidon.stepScale_nonneg
#print axioms Guidon.weight_interval
#print axioms Guidon.transcript_extensionality
#print axioms Guidon.projection_idempotent
#print axioms Guidon.dot_error_l1
#print axioms Guidon.stale_gain_lower
#print axioms Guidon.population_neutrality_error
#print axioms Guidon.floorScale_nonneg
#print axioms Guidon.floor_correction_bounded
#print axioms Guidon.floor_weight_interval
#print axioms Guidon.floor_weights_positive
#print axioms Guidon.floor_perturbation_energy
#print axioms Guidon.normalized_reconstruction
